/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firefighter.desktop;

import firefighter.core.API.RestAPIBase;
import firefighter.core.UniException;
import firefighter.core.Utils;
import firefighter.core.constants.Values;
import firefighter.core.entity.baseentityes.JEmpty;
import firefighter.core.entity.subjectarea.WorkSettings;
import firefighter.core.entity.users.User;
import retrofit2.Call;
import retrofit2.Response;

import java.util.ArrayList;

/**
 *
 * @author romanow
 */
public class Client<T extends MainBaseFrame> extends MainBaseFrame {
    public final static int mesW=600;
    public final static int shortView=BasePanel.PanelW+20;
    public final static int fullView=BasePanel.PanelW+mesW+20;
    public final static int ViewHight = BasePanel.PanelH+100;
    private Login loginForm=null;
    private I_OK disposeBack = null;
    private ArrayList<I_PanelEvent> panels = new ArrayList();
    private boolean secondForm=false;
    private void login(){
        setVisible(false);
        if (loginForm!=null)
            loginForm.setVisible(true);
        else
        loginForm = new Login(this,new I_Button(){
            @Override
            public void onPush() {
                startUser();
                Client.this.setVisible(true);
                }
            });
        }

    public Client() {
        secondForm=false;
        Values.init();
        initComponents();
        setMES(MES);
        login();
        }

    public Client(RestAPIBase service0, User user0, I_OK disposeBack0) throws UniException{
        Values.init();
        initComponents();
        disposeBack = disposeBack0;
        secondForm=true;
        service = service0;
        loginUser = user0;
        debugToken = user0.getSessionToken();
        loadConstants();
        startUser();
        }
    public void startUser(){
        try {
            setTitle("Mongo-сервер данных: "+loginUser.getHeader());
            debugToken = loginUser.getSessionToken();
            setMES(MES);
            ShowLog.setSelected(true);
            setBounds(100, 50, fullView, ViewHight);
            PanelList.setBounds(10,10,BasePanel.PanelW,BasePanel.PanelH);
            MES.setBounds(BasePanel.PanelW+10,10,mesW,BasePanel.PanelH);
            ShowLog.setSelected(true);
            PanelList.removeAll();
            panels.clear();
            WorkSettings ws = new APICall2<WorkSettings>(){
                @Override
                public Call<WorkSettings> apiFun() {
                    return service.workSettings(debugToken);
                    }
                }.call(this);
            for(PanelDescriptor pp : panelDescList){
                boolean bb=false;
                boolean editMode = true;
                for(int vv : pp.userTypes)
                    if (Math.abs(vv)==loginUser.getTypeId()){
                        bb=true;
                        editMode = vv > 0;
                        break;
                    }
                if (bb){
                    BasePanel panel = (BasePanel) pp.view.newInstance();
                    panel.editMode = editMode;
                    panel.initPanel(this);
                    panels.add(panel);
                    PanelList.add(pp.name, panel);
                    }
                }

            BasePanel pn;
            refresh();
            } catch(Exception ee){
                System.out.println(ee.toString());
                ee.printStackTrace();
                }
        }
    public void refresh(){
        refreshMode=true;
        for(I_PanelEvent xx : panels)
            xx.refresh();
        refreshMode=false;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MES = new java.awt.TextArea();
        PanelList = new javax.swing.JTabbedPane();
        ShowLog = new javax.swing.JCheckBox();
        MESLOC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(MES);
        MES.setBounds(720, 10, 570, 730);

        PanelList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PanelList);
        PanelList.setBounds(10, 10, 700, 700);

        ShowLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowLog.setText("->");
        ShowLog.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ShowLogItemStateChanged(evt);
            }
        });
        getContentPane().add(ShowLog);
        ShowLog.setBounds(650, 720, 50, 25);
        getContentPane().add(MESLOC);
        MESLOC.setBounds(10, 720, 630, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void logOff(){
        if (secondForm){
            dispose();
            return;
            }
        for(I_PanelEvent xx : panels)
            xx.shutDown();
        try {
            Response<JEmpty> res = service.logoff(debugToken).execute();
            if (!res.isSuccessful()){
                System.out.println("Ошибка сервера: "+ Utils.httpError(res));
                }
            loginForm.disConnect();
            login();
            }catch (Exception ee){
                System.out.println("Ошибка сервера: "+ee.toString());
                loginForm.disConnect();
                login();
                }
        }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logOff();
        if (disposeBack!=null)
            disposeBack.onOK(null);
    }//GEN-LAST:event_formWindowClosing

    private void ShowLogItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ShowLogItemStateChanged
        setBounds(100, 50, ShowLog.isSelected()? fullView : shortView, ViewHight);
        if (ShowLog.isSelected()) setMES(MES); else setMES(MESLOC);
    }//GEN-LAST:event_ShowLogItemStateChanged
    //------------------------------------------------------------------------------------------------------------------
    public void sendEvent(int code, long par2){
        sendEventPanel(code,0,par2,"");
        }
    public void sendEventPanel(int code, int par1, long par2, String par3){
        if (refreshMode) return;
        for(I_PanelEvent xx : panels)
            xx.eventPanel(code, par1,par2,par3);
    }
    public void panelToFront(BasePanel pp){
        for (int i=0;i<panels.size();i++)
            if (panels.get(i) == pp) {
                PanelList.setSelectedIndex(i);
                break;
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea MES;
    private javax.swing.JTextField MESLOC;
    private javax.swing.JTabbedPane PanelList;
    private javax.swing.JCheckBox ShowLog;
    // End of variables declaration//GEN-END:variables
}
