/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firefighter.desktop;

import java.awt.Rectangle;

/**
 *
 * @author romanow
 */
public class Message extends javax.swing.JFrame {
    private I_Button ok;
    /**
     * Creates new form OK
     */
    public Message(int x,int y,String title) {
        this(x,y,title,null);
        }
    public Message(int x,int y,String title, I_Button ok0) {
        initComponents();
        ok = ok0;
        UtilsDesktop.setLabelText(Text,title,60);
        setBounds(x+20,y+20,450,200);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OK = new javax.swing.JButton();
        Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(180, 110, 70, 30);
        getContentPane().add(Text);
        Text.setBounds(20, 10, 410, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        dispose();
        if (ok!=null)
            ok.onPush();
    }//GEN-LAST:event_OKActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JLabel Text;
    // End of variables declaration//GEN-END:variables
}
